#!/usr/bin/env python3
"""Generate Android resources and the canonical-result translation index. No network access."""
from pathlib import Path
import hashlib, re, html, json, argparse
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'localization/translations.tsv'
BASE = ROOT / 'android-app/core/src/main'
TOKEN = re.compile(r'\$\{[^{}]*\}|\$[A-Za-z_][A-Za-z0-9_]*')
def normalize(text):
    count = 0
    def replacement(_):
        nonlocal count
        count += 1
        return f'%{count}$s'
    return TOKEN.sub(replacement, text)
def load():
    entries = {}
    for line_no, line in enumerate(SOURCE.read_text().splitlines(), 1):
        if not line or line.startswith('#'): continue
        parts = line.split('|')
        if len(parts) != 3 or any(not p for p in parts): raise ValueError(f'Invalid row {line_no}')
        english, hi, gu = parts
        english = normalize(english)
        placeholders = sorted(re.findall(r'%\d+\$s', english))
        for translated in (hi, gu):
            if sorted(re.findall(r'%\d+\$s', translated)) != placeholders:
                raise ValueError(f'Placeholder mismatch at {line_no}: {english}')
        value = (hi, gu)
        if english in entries and entries[english] != value: raise ValueError(f'Conflicting duplicate {line_no}: {english}')
        entries[english] = value
    return entries

def build(entries):
    resources = {language: ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated by scripts/generate_localization.py; edit localization/translations.tsv. -->', '<resources>'] for language in ('en', 'hi', 'gu')}
    kotlin = ['package com.sentinel.ai.core.i18n', '', 'import com.sentinel.ai.core.R', '', '// Generated; canonical English persists in history, translations are applied only for display.', 'internal object TranslationCatalog {', '    val entries: List<Pair<String, Int>> = listOf(']
    def escape_xml(value):
        return html.escape(value, quote=False).replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')
    for english, (hi, gu) in entries.items():
        key = 'sx_' + re.sub(r'[^a-z0-9]+', '_', english.lower()).strip('_')[:44] + '_' + hashlib.sha256(english.encode()).hexdigest()[:8]
        for language, value in zip(('en', 'hi', 'gu'), (english, hi, gu)):
            resources[language].append(f'    <string name="{key}" formatted="false">"{escape_xml(value)}"</string>')
        quoted = json.dumps(english, ensure_ascii=False).replace('$', '\\$')
        kotlin.append(f'        {quoted} to R.string.{key},')
    kotlin.extend(['    )', '}', ''])
    out = {BASE/'java/com/sentinel/ai/core/i18n/TranslationCatalog.kt': '\n'.join(kotlin)}
    for language, lines in resources.items():
        lines.extend(['</resources>', ''])
        out[BASE/'res'/('values' if language == 'en' else f'values-{language}')/'safex_strings.xml'] = '\n'.join(lines)
    return out
if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    entries = load(); files = build(entries)
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, value in files.items() if not path.exists() or path.read_text() != value]
        if stale: raise SystemExit('Stale localization resources: ' + ', '.join(stale))
    else:
        for path, value in files.items(): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(value)
    print(f'{len(entries)} strings; en/hi/gu keys and placeholders match; generated files {"checked" if args.check else "updated"}.')
